### ISSUE TITLE
Bitmap envmap in Use Max Procedural Maps does not work?

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed-max#111]

**Comment by usakhelo** [comment]
I checked and it works, but strangely in coordinates Texture mapping type should be chosen and not Environment.

**Comment by dictoon** [comment]
Indeed, I'm finding the same thing.

What most likely happens is that appleseed's lat-long environment EDF does coordinates transformation itself, so it expects the input texture to use the classical rectangular parameterization.

This should go into our hypothetical documentation, but it doesn't appear to be a bug. Closing it.
