### ISSUE TITLE
When a texture is bound to an input, the color/slider has no effect

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed-max#12]

**Comment by juancarlosgzrz** [comment]
I don't think this is a bug, usually other renders block their sliders/colors, they have no effect because value is directly taken from texture/map. It really got me when i found out this, if you want to modify effect then you color correct the texture map or use the output rollout. But if we want to to this way I don't know, it's new @dictoon @usakhelo   I'd like to hear your opinion > @luisbarrancos

**Comment by usakhelo** [comment]
I agree it's different in appleseed. Usually, let's say in standard Max material, you have a color, then a texture and then a texture weight. So if weight is 100 then texture replaces the color.
In appleseed color is the weight, so when you don't have texture only color "weight" affects parameter. When you have a texture then color affects texture input.

**Comment by usakhelo** [comment]
So, basically right now you have fewer parameters, which is not bad. Question is if you can achieve everything you need.

**Comment by juancarlosgzrz** [comment]
Actually is the other way around, you have more parameters when you your sliders and textures can be modifiedand both affect the final look, it's a bit confusing IMHO

**Comment by usakhelo** [comment]
Got it, so in order to have texture to fully drive the parameter, you first assign the texture and then you have to set spinner to 100. I agree it may be confusing.

**Comment by usakhelo** [comment]
Ok, I should clarify probably - I'm talking about the mode when Max procedurals are off.

**Comment by juancarlosgzrz** [comment]
Ah, yeah, it explains everything. Why max procedurals are relevant right now?

**Comment by usakhelo** [comment]
I thought everyone wants support of max procedurals so... It just there in case you need it.
It'll be gone someday in future.

**Comment by luisbarrancos** [comment]
I'm not sure i understood this correctly, if i haven't, apologies in advance. But in my experience, the users connect a texture map to a color input, whatever that might be. And sometimes they just want to keep the texture connected and vary the weight on the shader - either to check a particular look while doing the material appearance on the asset, or drive it by a expression, keyframe it, whatever. 

They could do that by using some kind of color correction node connecting between a texture and the shader input - that's completely valid, but most of the times they want a simple tweak, so usually a simple [0,1] weight is all it's needed, and we leave color correction nodes to provide much more complex functionality (i.e, saturation, hue changes, gain/bias, and so on).
What can be done to avoid a mass of textures, is usually having a color slot for the input texture, and a weight, non-texturable (but keyable). Imho that ends up being the more user friendly approach.

**Comment by juancarlosgzrz** [comment]
So is it valid? never heard of that workflow/style before.

**Comment by usakhelo** [comment]
I'm closing this, right?
