### ISSUE TITLE
Anisotropy not working in appleseed Metal

### ISSUE THREAD

**Issue by juancarlosgzrz** [appleseedhq/appleseed-max#120]
Totally not working

**Comment by usakhelo** [comment]
I need to check this. Is it faulty max parameter or metal shader lacks parameter? May be I didn't bind them correctly...

**Comment by usakhelo** [comment]
I'm closing this, right? Or I should fix anisotropy in `Use procedurals` mode probably...

**Comment by dictoon** [comment]
Before closing this ticket, we need to get confirmation from @juancarlosgzrz that metal's anisotropy is working as expected both when `Use Max Procedurals Maps` is checked and unchecked.

**Comment by juancarlosgzrz** [comment]
Definitely working. I'll close this and if I find anything further related to anisotropy I'll let you know guys.
