### ISSUE TITLE
Renderstamp - Feature

### ISSUE THREAD

**Issue by juancarlosgzrz** [appleseedhq/appleseed-max#124]
Hi, in order to spread the word, we should have a render stamp that prints basic scene info, render time and also, most important appleseed logo. Not top priority.  Cheers

**Comment by usakhelo** [comment]
I won't be surprised it is already implemented in appleseed.

**Comment by dictoon** [comment]
On my mind for many, many years :) But unfortunately not supported yet. I'll close this ticket and open a new one in appleseed's issue tracker.

**Comment by dictoon** [comment]
Here we go: https://github.com/appleseedhq/appleseed/issues/1787. Feel free to provide more details if I missed anything.

**Comment by juancarlosgzrz** [comment]
Cool! thanks!

**Comment by juancarlosgzrz** [comment]
We could need that, when we render those random walk images n.n

**Comment by dictoon** [comment]
It's quite a bit more work than it looks, to do it properly we need to bring in a 2D rendering library with text support. We could do it in a simpler way, but we have various other needs for high quality, antialiased 2D primitives such as lines so let's kill two birds with one stone.
