### ISSUE TITLE
Replace dots by spaces in OSL shaders' section names

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed-max#137]
E.g. in the case of asStandardSurface, change "Specular.Anisotropy" to "Specular Anisotropy".

**Comment by est77** [comment]
dots are markers for subgroups. Specular.Anisotropy means Anisotropy section inside the Specular section. They are not supposed to be visible in UIs.

**Comment by juancarlosgzrz** [comment]
That makes sense

**Comment by usakhelo** [comment]
Adding link to appleseed ticket [Improve as_standard_surface ergonomy](https://github.com/appleseedhq/appleseed/issues/1900#issuecomment-374207408)

**Comment by usakhelo** [comment]
This can be closed probably.

**Comment by dictoon** [comment]
Absolutely. Feel free to close tickets yourself when they are done.

**Comment by juancarlosgzrz** [comment]
Should this be re-opened?

**Comment by dictoon** [comment]
@juancarlosgzrz Why would it need to be opened?
