### ISSUE TITLE
Add alpha to SSS material

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed-max#14]

**Comment by dictoon** [comment]
@juancarlosgzrz In your opinion, is this issue still relevant? Is there currently a way to have both SSS and alpha transparency/cutout on an object, say a tree leaf?

**Comment by dictoon** [comment]
In any case, if we decide to add an alpha parameter, it should be called `Alpha` and vary from 0 to 100 (percents).

Another point to check is whether we want to update the built-in shader (not based on OSL), or the OSL shader (the one you pointed out), or both.

**Comment by juancarlosgzrz** [comment]
> @juancarlosgzrz In your opinion, is this issue still relevant? Is there currently a way to have both SSS and alpha transparency/cutout on an object, say a tree leaf?

Is still relevant, and there's no workaround, in that case I would blend two shaders together, the leaf material and a transparent material and mask them, but that way creates more unnecessary and complex shader trees.  

I would vote yes

**Comment by dictoon** [comment]
Done.
