### ISSUE TITLE
Pixel Time renderer elements is always black

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed-max#173]

**Comment by usakhelo** [comment]
Hi @dictoon,
Are trying to open it with xnview? It can't open it properly, nor can max. I open these files in Blackmagic Fusion:
![image](https://user-images.githubusercontent.com/1850877/39398946-73afcb80-4ae3-11e8-8655-7aadbb10ddf8.png)

**Comment by dictoon** [comment]
I had tried first with xnview, then with exrdisplay to make sure I wasn't missing something. Turns out that even exrdisplay doesn't get it right, while Tev does. Working as expected. Thanks!
