### ISSUE TITLE
Project export fails when materials use Max procedural textures

### ISSUE THREAD

**Issue by Mango-3** [appleseedhq/appleseed-max#175]
No appleseed project file is exported when the scene contains materials with MAX procedural textures assigned even though the scene renders without issue inside MAX (see screenshot)
I'm not sure if this is a bug of the current exporter or a feature which is not implemented. In the test scene I assigned two different substance materials which generate the textures for the appleseed DisneyMtl internally. 
Screenshot attached:
![scene_export_fails_max_proc_textures](https://user-images.githubusercontent.com/22252558/39445414-a220b736-4cc3-11e8-9c06-a33971a98771.PNG)

**Comment by dictoon** [comment]
@usakhelo Can we disable (gray out) exporting when Use Max Procedural Maps is checked?

**Comment by usakhelo** [comment]
I think we can.

**Comment by Mango-3** [comment]
A quick fix would be to change the text next to the checkbox from "use Max Procedural Maps (non-compatible mode)" to "use Max Procedural Maps (disables scene export)"

**Comment by dictoon** [comment]
@Mango-3 Totally! I never liked that "non-compatible mode" mention, non-compatible with what? I much prefer "disables scene export". We should do both: the mention and actually graying out export options. 

Thnaks for your input!

**Comment by Mango-3** [comment]
Nicely done Sergo! Much less confusing now.
