### ISSUE TITLE
Render fails when connecting the same alpha map to two different materials

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed-max#19]
> I had two materials that were going to use the same alpha map. When connecting the one map to each materials alpha slot the render fails to start (the 'poof' effect). Copying the bitmap and connecting each bitmap tthe alpha slots independently allows the render to run.

**Comment by juancarlosgzrz** [comment]
I couldn't repro this in OSL. All fine

**Comment by usakhelo** [comment]
I think the original bug was fixed long time ago.
