### ISSUE TITLE
Checkbox spacing is inconsistent

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed-max#198]
Vertical spacing of the checkboxes in the System section isn't consistent with vertical spacing of checkboxes in other sections such as the Lighting section:

![image](https://user-images.githubusercontent.com/321290/44063754-39376eb2-9f62-11e8-8191-adcd9c727c72.png)

**Comment by Mango-3** [comment]
Fixed with beb2970 

![image](https://user-images.githubusercontent.com/22252558/44983068-8c573400-af80-11e8-8b1b-ca3e9e4fa495.png)
