### ISSUE TITLE
Animated material parameters don't work

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed-max#212]
From @frang on Discord:

> I've been testing the appleseed-max2017-1.0.0-beta-preview1. I noticed something that doesn't work: when you animate a material parameter and you render a series of frames, the animated param doesn't change along them. If you render frames individually it works.

**Comment by usakhelo** [comment]
I confirm this and this is applied to OSL materials.

**Comment by dictoon** [comment]
Done.
