### ISSUE TITLE
Make bounce limit controls more intuitive

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed-max#230]
1. `Max Global Bounces` should be renamed to `Max Ray Bounces`: we remove the confusing word "global". **This control allows to set all bounce limits at once**.
2. The user can then _override_ this `Max Ray Bounces` setting on a per-bounce type basis: for this, he/she checks the checkbox next to a particular bounce type and enter a value. Only values <= `Max Ray Bounces` are allowed, i.e. he/she can't set `Max Ray Bounces` to 5 and `Max Diffuse Bounces` to 8.

**Comment by juancarlosgzrz** [comment]
Done :D

**Comment by dictoon** [comment]
Yes, thanks!
