### ISSUE TITLE
Possible typo

### ISSUE THREAD

**Issue by usakhelo** [appleseedhq/appleseed-max#239]
Hi @Mango-3 ,

I think this is a typo in paramblock. It worked for some reason, but looks like `ParamIdOptLightOutsideVolumes` is not assigned correct rollout id. It's `ParamMapIdLighting` instead of `ParamMapIdPathTracer`

https://github.com/appleseedhq/appleseed-max/blob/4d396c708f854b8b9649fc3fbecbbf4c9ebb8168/src/appleseed-max-impl/appleseedrenderer/appleseedrenderer.cpp#L1120

**Comment by usakhelo** [comment]
There's also a type here: https://github.com/appleseedhq/appleseed-max/blob/4d396c708f854b8b9649fc3fbecbbf4c9ebb8168/src/appleseed-max-impl/appleseedrenderer/appleseedrendererparamdlg.cpp#L546

**Comment by Mango-3** [comment]
Good catch @usakhelo
