### ISSUE TITLE
Bump mapping does not work with SSS material

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed-max#24]

**Comment by juancarlosgzrz** [comment]
appleseedSSSMtl

![image](https://user-images.githubusercontent.com/26150363/48376630-54efbc80-e680-11e8-8706-224ffe56124f.png)

asSubsurface

![image](https://user-images.githubusercontent.com/26150363/48376774-d5aeb880-e680-11e8-9b8f-50e2406c7bb4.png)


The issue is now long gone :)
