### ISSUE TITLE
Environment maps oriented differently than in Corona or V-Ray

### ISSUE THREAD

**Issue by juancarlosgzrz** [appleseedhq/appleseed-max#251]
When using HDRi bitmaps in environments, is shown wrong, compared to corona or Vray:

appleseed:

![image](https://user-images.githubusercontent.com/26150363/48865869-ba7d3080-ed85-11e8-95eb-7850202e124b.png)

Corona:

![image](https://user-images.githubusercontent.com/26150363/48865881-c7018900-ed85-11e8-9cfb-ef5599dc51d5.png)

**Comment by dictoon** [comment]
Not necessarily a bug but rather different orientation conventions between renderers. If Corona and V-Ray share the same convention, then appleseed should probably too.

**Comment by juancarlosgzrz** [comment]
That would be great!

**Comment by Mango-3** [comment]
I had a look at the issue. Compared to Corona/V-Ray appleseed env map is rotated by 90 deg. and reflected about the vertical axis (z-axis in Max). 
If you load a scene from Corona and want to render it in appleseed you would need to set `Offset_U = -0.5`and `Tiling_U = -1` for the HDRI-Bitmap.

I added the 90 deg. rotation in the code (not yet in a PR) and then one would just need to set the `Tiling U`parameter to -1 in the Max Bitmap Coordinates rollout (see screenshot). With this set, the render image coincides with the Max environment background preview in the viewport. 
![env_rotation](https://user-images.githubusercontent.com/22252558/49028190-78e7ed80-f1aa-11e8-8604-636f88e637f8.PNG)

appleseed Lat-Long environment-EDF does currently only support horizontal and vertical shifts, not reflections, so I cannot pass the reflection (Tiling_U = -1) to appleseed as a parameter similar to the rotations. 

![lat_long](https://user-images.githubusercontent.com/22252558/49028516-3d99ee80-f1ab-11e8-9e13-6b6a01d1f6cb.PNG)

**Comment by juancarlosgzrz** [comment]
So it needs an aditional parameter inside appleseed.core  in order to invert the HDRi?

**Comment by Mango-3** [comment]
Yes, that seems to be the conclusion.

**Comment by Mango-3** [comment]
Fixed with commit a980750

**Comment by juancarlosgzrz** [comment]
I'm getting same results with asmax and corona, this can be closed.

**Comment by dictoon** [comment]
Thanks!
