### ISSUE TITLE
Anisotropy leads to facetting artifacts

### ISSUE THREAD

**Issue by juancarlosgzrz** [appleseedhq/appleseed-max#252]
![image](https://user-images.githubusercontent.com/26150363/48866742-c1597280-ed88-11e8-9758-8ee3ccf6a4a0.png)

The example above, shows the faceted polygons  when using anisotropy at full.

**Comment by juancarlosgzrz** [comment]
With out anisotropy:

![image](https://user-images.githubusercontent.com/26150363/48866856-24e3a000-ed89-11e8-8031-c916bad775f4.png)

**Comment by Mango-3** [comment]
Seems for this to be fixed smooth tangents need to be implemented in the mesh exporter.

**Comment by juancarlosgzrz** [comment]
Is it merged into master?

**Comment by Mango-3** [comment]
Yes it is.

**Comment by juancarlosgzrz** [comment]
Solved, different anisotropy methods

![image](https://user-images.githubusercontent.com/26150363/64206878-4e6d4400-ce50-11e9-87d4-5d6bef880e2a.png)

![image](https://user-images.githubusercontent.com/26150363/64206888-562ce880-ce50-11e9-8622-db4dac2aa31d.png)

![image](https://user-images.githubusercontent.com/26150363/64206922-647b0480-ce50-11e9-9a71-e82234664889.png)
