### ISSUE TITLE
Allow adding and removal of OSL shaders parameters without breaking Max scenes

### ISSUE THREAD

**Issue by usakhelo** [appleseedhq/appleseed-max#275]
Currently no parameter can be added or removed from OSL shader. It will cause changing of the ID's of existing parameters and will break old scenes made with previous version of OSL shaders.
Can be fixed by adding parameter ID for each OSL parameter and re-using the ID in max plugin.

**Comment by usakhelo** [comment]
We are not closing this until it's proved to work, right?

**Comment by dictoon** [comment]
I think we can actually close this ticket. We've found a reasonable solution that's supposed to be robust, and implemented it. If for some reason it doesn't work then we should find out why and open a more focused ticket.
