### ISSUE TITLE
Support Explicit normals on 3ds max meshes

### ISSUE THREAD

**Issue by usakhelo** [appleseedhq/appleseed-max#299]
Some meshes in max don't have smoothing groups assigned. Instead there are one or more explicit normals. appleseed right now only supports meshes with smoothing groups, otherwise it builds normals based on face normals.

Attached is the test scene for max 2019. It is rendered faced while viewport shows smooth meshes.

[test_normal_export.zip](https://github.com/appleseedhq/appleseed-max/files/3292670/test_normal_export.zip)

**Comment by usakhelo** [comment]
I think I have the fix for that, I'll try to make PR this weekend.

**Comment by dictoon** [comment]
#300
