### ISSUE TITLE
Redundant GUI elements in appleseed-max2015-20151125

### ISSUE THREAD

**Issue by abushinov** [appleseedhq/appleseed-max#3]
![redundant gui elements](https://cloud.githubusercontent.com/assets/4364139/11435655/434d3ca2-94f6-11e5-905a-97ca69495caf.png)

**Comment by dictoon** [comment]
Fixed, thanks for reporting!

**Comment by abushinov** [comment]
no problem, you can also rid off from unused tabs in render settings dialog using this example:

"void CJRenderer::AddTabToDialog ( ITabbedDialog* dialog, ITabDialogPluginTab* tab )"
and
"int CJRenderer::AcceptTab ( ITabDialogPluginTab* tab )"
in
"C:\Program Files\Autodesk\3ds Max 2015 SDK\maxsdk\howto\render\cjrender\cjrui.cpp"
