### ISSUE TITLE
Move Background Alpha setting to Output panel

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed-max#325]
![image](https://user-images.githubusercontent.com/321290/65946183-dcc7ec00-e435-11e9-820e-a353c8b7098f.png)

**Comment by Mango-3** [comment]
Makes sense, maybe rename it to `Background Visibility` to make it clearer for new user.

**Comment by dictoon** [comment]
Hm, I would assume that the term *alpha* is well understood by users?

**Comment by juancarlosgzrz** [comment]
Yeah, sounds clear to me!

**Comment by Mango-3** [comment]
Implemented with commit b274c8dff3b9061e576d80e8d1f48ead4b73984b
