### ISSUE TITLE
Edge Reflectance Weight label does not fit within shader UI space 

### ISSUE THREAD

**Issue by Mango-3** [appleseedhq/appleseed-max#361]
Not sure how best to fix this, change the label to a shorter one or increase the space for labels in general in the OSL shader UI (increase width of shader window)
See screenshot:
![Capture](https://user-images.githubusercontent.com/22252558/78461539-a44de700-76d2-11ea-91ab-2ba7f3470297.PNG)

**Comment by dictoon** [comment]
I vote for the second option (increase width) since in general OSL shaders tend to use rather long labels for parameters.
