### ISSUE TITLE
Add a way to mix materials

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed-max#47]

**Comment by juancarlosgzrz** [comment]
Done

**Comment by usakhelo** [comment]
There is some issue but generally done yes.
@dictoon is it ok to close it, or we are cleaning up issues after each release?

**Comment by dictoon** [comment]
We can close issues as soon as they are fixed/implemented. I think we can close this one. If there are bugs related to blending, we'll open individual issues.
