### ISSUE TITLE
Glass material is dark in editor

### ISSUE THREAD

**Issue by makit3d** [appleseedhq/appleseed-max#49]
Glass materials show up as very dark in the editor.

Max 2016
appleseed-max2017-0.4.6-beta-preview1

![glass mats](https://user-images.githubusercontent.com/11532652/29585838-8dd08e4c-8756-11e7-9b42-fe4134469907.JPG)

**Comment by dictoon** [comment]
Due to `renderer_settings.m_background_emits_light` being set to false in `AppleseedRenderer::Render()` when rendering a material editor preview.

**Comment by dictoon** [comment]
Fixed.
