### ISSUE TITLE
Allow rotating environment maps

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed-max#55]

**Comment by usakhelo** [comment]
You can rotate env. maps with offset parameters. Is this about that kind of rotation?

**Comment by juancarlosgzrz** [comment]
Using bitmap options? they are kind of weird. What about supporting dome light?  It makes the job easier.

**Comment by usakhelo** [comment]
Probably it is possible to support standard sphere gizmo. You'll pick the gizmo the same way you choose directional light right now and it binds gizmo's transforms to the map coordinates.

**Comment by dictoon** [comment]
It's already possible to rotate an environment map horizontally and vertically using the U and V offsets:

![image](https://user-images.githubusercontent.com/321290/50113762-2a76bd80-0243-11e9-8e3b-7a6567d06b1a.png)

It would make sense to also allow rotating an environment map using the U/V/W angles:

![image](https://user-images.githubusercontent.com/321290/50113738-1b900b00-0243-11e9-9ba4-00603eefbced.png)

**Comment by Mango-3** [comment]
Fixed with commit a980750

**Comment by dictoon** [comment]
Confirmed done by @juancarlosgzrz.
