### ISSUE TITLE
appleseed-max2015-0.1.2-alpha: proposal to change extension for appleseed-stdmtl-max2015.dlm

### ISSUE THREAD

**Issue by abushinov** [appleseedhq/appleseed-max#6]
from 3ds max SDK documentation, topic "Plug-in File Extensions"
...
DLM - Modifiers
...
DLT - Materials and Textures. 

P.S this is doesn't affect how plugin work, just for "clean" name of the file.

**Comment by dictoon** [comment]
Fixed, thank you!

The fix will be available in the next release, since the wrong extension doesn't seem to cause real troubles (unless reported otherwise).
