### ISSUE TITLE
Maps slots shown incorrectly on Glass and SSS materials in Slate material editor mode

### ISSUE THREAD

**Issue by usakhelo** [appleseedhq/appleseed-max#62]
This affects map slot indexing. For example in Glass material if map is shown as connected to Bump Map slot it actually connected to Volume Color slot.
![image](https://user-images.githubusercontent.com/1850877/30610658-df687d26-9d4c-11e7-9c32-e56ec0cfbbe9.png)

**Comment by dictoon** [comment]
Fixed.
