### ISSUE TITLE
Add Plastic material based on as_plastic() closure

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed-max#67]

**Comment by luisbarrancos** [comment]
For reference, the maya/gaffer shader is here:
https://github.com/appleseedhq/appleseed/blob/master/src/appleseed.shaders/src/appleseed/as_plastic.osl

**Comment by dictoon** [comment]
Thanks! It makes sense to try using `as_plastic.osl` as is under the hood of appleseed Plastic Material.

**Comment by dictoon** [comment]
Done.
