### ISSUE TITLE
appleseed-max 0.1.3-alpha: appleseedStdMtl's animated diffuse color doesn't update in viewport

### ISSUE THREAD

**Issue by abushinov** [appleseedhq/appleseed-max#7]
video:
https://www.dropbox.com/s/ejft6demmnx3atk/Untitled.mp4?dl=0

3ds max file:
https://dl.dropbox.com/s/177qg1121z1bbzy/appleseed_animated_diffuse_2015_.max?dl=1

**Comment by dictoon** [comment]
Thanks for the detailed bug report, as usual!

I can reproduce the issue. A quick investigation showed that the code appears to behave correctly.

I've posted a [question](http://forums.cgsociety.org/showthread.php?p=8129575#post8129575) on CGTalk. In the meantime I'll continue investigating.

**Comment by dictoon** [comment]
Fixed. Thank you!
