### ISSUE TITLE
Non-bitmap environment map does not reflect camera motion

### ISSUE THREAD

**Issue by usakhelo** [appleseedhq/appleseed-max#71]
Something goes wrong when non-bitmap texture is re-rendered to appleseed's `MemoryTexture2d`.

**Comment by dictoon** [comment]
Not reproducable?

**Comment by usakhelo** [comment]
It was fixed I think. Should I add link to fixing commit?

**Comment by dictoon** [comment]
Sure, if you can find it easily.
