### ISSUE TITLE
Add support for true instancing

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed-max#78]

**Comment by usakhelo** [comment]
I'm closing this, right?

**Comment by usakhelo** [comment]
@juancarlosgzrz did you have a chance to check this feature?

**Comment by juancarlosgzrz** [comment]
Yes I did, it works not as much I like and is kind of unstable. Sometimes my pc would freeze when overexceeding memory limit. But it works, you can close it

**Comment by usakhelo** [comment]
Interesting.. may be you check the checkbox on non-instance objects?

**Comment by juancarlosgzrz** [comment]
That's a possibility but I make sure all my hand instanced objects were checked. I'll try later again and get back to you
