### ISSUE TITLE
Add appleseed Standard Material

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed-max#85]
We just need to build the UI, the shader itself is available here:
https://github.com/appleseedhq/appleseed/blob/master/src/appleseed.shaders/src/appleseed/as_standard_surface.osl

**Comment by dictoon** [comment]
Yes, as soon as the OSL support is merged.

**Comment by usakhelo** [comment]
Can I close this and other textures that are added with OSL plugin?

**Comment by dictoon** [comment]
Yes! Closing this one now.
