### ISSUE TITLE
Disabling GI also disables refraction through glass

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed-max#9]

**Comment by juancarlosgzrz** [comment]
![image](https://user-images.githubusercontent.com/26150363/48375623-61bee100-e67d-11e8-971d-027a64ec6850.png)

![image](https://user-images.githubusercontent.com/26150363/48375711-9894f700-e67d-11e8-876d-8ce5d16185a2.png)

Disabling GI no longer disables refraction, as shown above. _(1)  Enabled, (2) Disabled_
