### ISSUE TITLE
Allow adjusting exposure of HDRI environment map

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed-max#95]

**Comment by usakhelo** [comment]
We can use Output parameter of the Output rollout and bind it to the texture shader's Multiplier parameter? Or it should be a separate osl shader to multiple texture output?

**Comment by dictoon** [comment]
> We can use Output parameter of the Output rollout

Which output parameter? Does it already exist?

> Or it should be a separate osl shader to multiple texture output?

It doesn't have to be an OSL shader, we can simply adjust the radiance multiplier in the environment EDF. The main question is indeed where to store this parameter (and possibly other related ones).

V-Ray has a dedicated map, VRayHDRI for that. Maybe we need to do the same?

**Comment by usakhelo** [comment]
Output Amount parameter is in the Output rollout of bitmap texture. It's not an exposure but we can treat it like that.

**Comment by dictoon** [comment]
Done.
